// Autogenerated from Pigeon (v4.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface Message ()
+ (Message *)fromMap:(NSDictionary *)dict;
+ (nullable Message *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation Message
+ (instancetype)makeWithSubject:(NSString *)subject
    body:(NSString *)body
    email:(NSString *)email {
  Message* pigeonResult = [[Message alloc] init];
  pigeonResult.subject = subject;
  pigeonResult.body = body;
  pigeonResult.email = email;
  return pigeonResult;
}
+ (Message *)fromMap:(NSDictionary *)dict {
  Message *pigeonResult = [[Message alloc] init];
  pigeonResult.subject = GetNullableObject(dict, @"subject");
  NSAssert(pigeonResult.subject != nil, @"");
  pigeonResult.body = GetNullableObject(dict, @"body");
  NSAssert(pigeonResult.body != nil, @"");
  pigeonResult.email = GetNullableObject(dict, @"email");
  NSAssert(pigeonResult.email != nil, @"");
  return pigeonResult;
}
+ (nullable Message *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [Message fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"subject" : (self.subject ?: [NSNull null]),
    @"body" : (self.body ?: [NSNull null]),
    @"email" : (self.email ?: [NSNull null]),
  };
}
@end

@interface MessageApiCodecReader : FlutterStandardReader
@end
@implementation MessageApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [Message fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface MessageApiCodecWriter : FlutterStandardWriter
@end
@implementation MessageApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[Message class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface MessageApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation MessageApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[MessageApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[MessageApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *MessageApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    MessageApiCodecReaderWriter *readerWriter = [[MessageApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void MessageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MessageApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MessageApi.getMessages"
        binaryMessenger:binaryMessenger
        codec:MessageApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getMessagesEmail:error:)], @"MessageApi api (%@) doesn't respond to @selector(getMessagesEmail:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_email = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSArray<Message *> *output = [api getMessagesEmail:arg_email error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
